name = "ftt-telegram-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "BOT_KV"
id = "39653d1f9b5147259cf3791658f131d7"

[[services]]
binding = "SIGNAL_WORKER"
service = "asignal"

